# Generated by Django 6.0 on 2026-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0027_ongs_description_ongs_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupom',
            name='quant',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
