# Generated by Django 6.0 on 2026-07-20 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0028_cupom_quant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupom',
            name='quant',
        ),
        migrations.RemoveField(
            model_name='cupom',
            name='usado',
        ),
        migrations.CreateModel(
            name='UserCupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.PositiveIntegerField(default=0)),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ecommerce.cupom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cupom')},
            },
        ),
    ]
