# Generated by Django 6.0 on 2026-07-20 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0029_remove_cupom_quant_remove_cupom_usado_usercupom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercupom',
            name='cupom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app_ecommerce.cupom'),
        ),
        migrations.AlterField(
            model_name='usercupom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to=settings.AUTH_USER_MODEL),
        ),
    ]
