# Generated by Django 6.0 on 2026-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0029_remove_cupom_quant_remove_cupom_usado_usercupom'),
        ('authentication', '0012_remove_user_cupom_user_cupom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cupom',
        ),
        migrations.AddField(
            model_name='user',
            name='cupom',
            field=models.ManyToManyField(
                blank=True, through='app_ecommerce.UserCupom', to='app_ecommerce.cupom'),
        ),
    ]
